services:

  mysql:
    container_name: final-agrix-db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: final-agrix